apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-test
  labels:
    app: nfs-pvc-test
spec:
  storageClassName: nfs-storageclass # SAME NAME AS THE STORAGECLASS
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 100Mi