
- name: "install haproxy version {{ _version }}"
  apt: name="haproxy={{ _version }}.*" state=present update_cache=yes force=yes
  when: _version is defined

- name: install haproxy latest
  apt: name=haproxy state=present update_cache=yes
  when: _version is not defined
  

- name: Update /etc/haproxy/haproxy.cfg
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    insertafter: EOF
    block: "{{ lookup('template', 'proxy.template') }}"

  notify:
  - restart haproxy


- name: Check PID of existing haproxy process
  shell: "ps -ef | grep haproxy"
  register: haproxy_status
- debug: "msg={{ haproxy_status.stdout }}"