
- name: install haproxy
  apt: name="haproxy=1.6.*" state=present update_cache=yes force=yes

- name: Update /etc/haproxy/haproxy.cfg
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    insertafter: EOF
    block: "{{ lookup('template', 'proxy.template') }}"
  notify:
  - restart haproxy

- name: Check PID of existing haproxy process
  shell: "ps -ef | grep haproxy"
  register: haproxy_status
- debug: "msg={{ haproxy_status.stdout }}"