- hosts: "cntrl"
  become: true
  tasks:
  - name: install kubectl
    shell: |
      curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/bin/kubectl
      mkdir -p ~/.kube
  

- hosts: "master1"
  become: true
  tasks:
  - name: Fetch the file from the master to buffer
    fetch: src=/etc/kubernetes/admin.conf  dest=/tmp/ flat=yes
  

- hosts: "cntrl"
  become: true
  tasks:
  - name: Copy the file from buffer to proxy
    copy: src=/tmp/admin.conf   dest=/root/.kube/config



- hosts: "cntrl"
  become: true
  tasks:
  - shell: kubectl get nodes 
    register: get_nodes
  - debug: msg={{ get_nodes.stdout }}

  - shell: kubectl get pods -A
    register: get_pods
  - debug: msg={{ get_pods.stdout }}

  - shell: kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml
    register: apply_calico
  - debug: msg={{ apply_calico.stdout }}




- hosts: cntrl
  become: true
  vars:
    - tags:
      - proxy
      - nfs
  tasks:
  - shell: "kubectl label node {{ item[0] }}  infra:{{ item[1] }}=true"
    when: 
    - hostvars[item.0].dedicated is defined
    - hostvars[item.0]['dedicated'] is search(item.1)
    with_nested:
    - "{{ groups['worker'] }}"
    - "{{ tags }}"

  - shell: "kubectl taint node {{ item }}  dedicated=infra:NoSchedule"
    when: 
    - hostvars[item].dedicated is defined
    with_items:
    - "{{ groups['worker'] }}"






