
- hosts: "master, worker"
  become: true
  tasks:
  - name: reset kubeadm 
    shell: "kubeadm reset -f "
  - name: remove kubelet
    shell: "apt remove kubelet -y "
  - name: remove kubectl 
    shell: "apt remove kubectl -y "
  - shell: "rm -rf /root/.kube"