
- hosts: proxy
  become: true
  vars_files:
    - vars/var_kubernetes.yaml

  tasks:

    - name: install haproxy
      apt: name="haproxy=1.6.*" state=present update_cache=yes force=yes

    - name: Update /etc/haproxy/haproxy.cfg
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        insertafter: EOF
        block: |
          ## Updated by Ansible ##
          frontend web_clinet
              bind *:443
              option tcplog
              mode tcp
              default_backend web_nodes
          backend web_nodes
              mode tcp
              balance roundrobin
              option ssl-hello-chk
              server ingcntrl01 infra1.openkube.io:30001 check
              server ingcntr02 infra2.openkube.io:30001 check
          
          frontend kube_client
              bind *:6443
              option tcplog
              mode tcp
              default_backend kube_nodes
          backend kube_nodes
              mode tcp
              balance roundrobin
              option ssl-hello-chk
              server master01 master1.openkube.io:6443 check
              server master02 master2.openkube.io:6443 check
              server master03 master3.openkube.io:6443 check
      notify:
        - Restart haproxy


    - name: Check PID of existing haproxy process
      shell: "ps -ef | grep haproxy"
      register: haproxy_status
      - debug: var=haproxy_status.stdout  


  handlers:
    - name: Restart haproxy
      systemd:
        name: haproxy
        state: restarted   
